= Culture générale
Dhrions
Version 2.0.0, 20/08/2025
// Document attributes
:sectnums:                                                          
:toc:                                                   
:toclevels: 5  
:toc-title: Sommaire

:description: Example AsciiDoc document                             
:keywords: AsciiDoc                                                 
:imagesdir: ./images
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: ./js

// Mes variables
:url-wiki: https://fr.wikipedia.org/wiki
:url-wiki-Europe-Ouest: {url-wiki}/Europe_de_l%27Ouest

== TL;DR

Ma documentation de culture générale est accessible en ouvrant link:main/build/antora/index.html[] avec un navigateur web.

Si le dossier `/build` n'existe pas, il faut générer la documentation.
Pour ce faire, on peut exécuter la commande suivante depuis le dossier `/main` :

[source, bash]
antora antora-playbook.yml

Si Antora n'est pas installé, on peut consulter link:https://docs.antora.org/antora/latest/install-and-run-quickstart/#install-antora[cette section] de la page dédiée à l'installation du site officielle d'Antora.

Pour générer un digest du dépôt, on peut taper, depuis la racine du dépôt :

[source, bash]
gitingest -e digest.txt -e *build -e *env -e *cercle*

== Documentation

De la documentation sur le présent dépôt est présent en ouvrant link:docs/build/antora/index.html[] avec un navigateur web.